---
title: "Week 1"
author: "Gregory Biland"
date: "4/28/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tmap)
library(readr)        # to import tabular data (e.g. csv)
library(dplyr)        # to manipulate (tabular) data
library(ggplot2)
library(terra)
library(sf)


dataFolder   <- here::here()   
RFolder      <- here::here()         
figureFolder <- here::here("figs") 
```


```{r}

wildschwein_BE <- read_delim(file.path(dataFolder, "wildschwein_BE.csv"))

```

# task 1 ########################################################################

```{r}

# Check Timezone
attr(wildschwein_BE$DatetimeUTC,"tzone") # or
wildschwein_BE$DatetimeUTC[1]

```

# task 2 ########################################################################

```{r}
ggplot(wildschwein_BE, aes(Long,Lat, colour = TierID)) +
  geom_point() +
  theme(legend.position = "none")

wildschwein_BE_sf <- st_as_sf(wildschwein_BE, 
                              coords = c("Long", "Lat"), 
                              crs = 4326)

wildschwein_BE_sf <- st_transform(wildschwein_BE_sf, crs = 2056)

# subset rows
wildschwein_BE_sf[1:10,]
wildschwein_BE_sf[wildschwein_BE_sf$TierName == "Sabi",]

# subset colums
wildschwein_BE_sf[,2:3]

wildschwein_BE <- st_as_sf(wildschwein_BE, 
                          coords = c("Long", "Lat"), 
                          crs = 4326)

rm(wildschwein_BE_sf)
```

# task 3 ########################################################################

```{r}
wildschwein_BE_grouped <- group_by(wildschwein_BE,TierID)
wildschwein_BE_smry <- summarise(wildschwein_BE_grouped)

wildschwein_BE_smry

mcp <- st_convex_hull(wildschwein_BE_smry)


```


# task 4 ########################################################################

```{r}

plot(mcp)

ggplot(mcp,aes(fill = TierID)) +
  geom_sf(alpha = 0.4)

ggplot(mcp,aes(fill = TierID)) +
  geom_sf(alpha = 0.4) +
  coord_sf(datum = 2056)

pk100_BE <- terra::rast(file.path(dataFolder, "pk100_BE.tif"))

pk100_BE

plotRGB(pk100_BE)

```

# task 5 ########################################################################

```{r}
tm_shape(pk100_BE) + 
  tm_rgb() 


tm_shape(pk100_BE) + 
  tm_rgb() +
  tm_shape(mcp) +
  tm_polygons(col = "TierID",alpha = 0.4,border.col = "red") +
  tm_legend(bg.color = "white")
```

# task 6 ########################################################################

```{r}
tmap_mode("plot")

tm_shape(mcp) +
  tm_polygons(col = "TierID",alpha = 0.4,border.col = "red") +
  tm_legend(bg.color = "white")
```
