---
title: "GEO880 - CMA: Exercise 3"
author: "Gregory Biland"
date: "5/3/2022"
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: no
  pdf_document:
    toc: yes
    toc_depth: '3'
    fig_caption: yes
  word_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo = FALSE, warning = FALSE, message = FALSE}
Sys.setenv(LANG = "en")
library(readr)        # to import tabular data (e.g. csv)
library(dplyr)        # to manipulate (tabular) data
library(ggplot2)      # to visualize data
library(sf)           # to handle spatial vector data
library(terra)        # To handle raster data
library(lubridate)    # To handle dates and times
library(grid)
library(gridExtra)
library(zoo)
library(SimilarityMeasures)

knitr::opts_chunk$set(
  message = F,
  fig.width = 7,
  fig.height = 6,
  pandoc.stack.size = "4g",
  fig.align = 'center',
  opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
)

dataFolder   <- here::here()   
RFolder      <- here::here()         
figureFolder <- here::here("figs") 
```

```{r data}
caro <- read_delim(file.path(dataFolder, "caro60.csv"))
caro <- as.data.frame(caro)
```

## Task 1
The sampling interval for this data set is 1 minute. Use a temporal window  v of 6 minutes, i.e. a window size of 6 positions (n±3).

```{r}
caro <- caro %>%
  mutate(
    nMinus3 = sqrt((lag(E,3)-E)^2+(lag(N,3)-N)^2),   # distance to pos -3 minutes
    nMinus2 = sqrt((lag(E,2)-E)^2+(lag(N,2)-N)^2),   # distance to pos -2 minutes
    nMinus1 = sqrt((lag(E,1)-E)^2+(lag(N,1)-N)^2),   # distance to pos -1 minutes
    nPlus1  = sqrt((E-lead(E,1))^2+(N-lead(N,1))^2), # distance to pos +1 mintues
    nPlus2  = sqrt((E-lead(E,2))^2+(N-lead(N,2))^2),  # distance to pos +2 minutes
    nPlus3  = sqrt((E-lead(E,3))^2+(N-lead(N,3))^2)  # distance to pos +3 minutes
  )

caro <- caro %>%
  rowwise() %>%
  mutate(
    stepMean = mean(c(nMinus3,nMinus2, nMinus1,nPlus1,nPlus2,nPlus3))
  ) %>%
  ungroup()
```

## Task 2

```{r}
hist(caro$stepMean)
summary(caro$stepMean)

caro <- caro %>% 
  ungroup() %>%
  mutate(static = stepMean < 10) #When the stepmean is smaller than 10, all the movement is considered as static, otherwise the movement is non-static

caro_filter <- caro %>%
  filter(!static)

```

## Task 3

```{r}
caro_filter%>%
  ggplot(aes(E, N, col = static))  +
  geom_path() +
  geom_point() +
  coord_equal() +
  theme(legend.position = "right")+
  ggtitle("Moving window reduced movement pattern of wild boars")+
  labs(colour="Is- Static")

caro%>%
  ggplot(aes(E, N, col = static))  +
  geom_path() +
  geom_point() +
  coord_equal() +
  theme(legend.position = "right")+
  ggtitle("None- reduced movement pattern of wild boars")+
  labs(colour="Is- Static")

```

## Task 4

```{r}
rle_id <- function(vec){
  x <- rle(vec)$lengths
  as.factor(rep(seq_along(x), times=x))
}

caro <- caro %>%
  mutate(segment_id = rle_id(static))

caro_seg_filter <- caro %>%
  filter(!static)

caro_seg5 <- caro_seg_filter %>%
  group_by(segment_id) %>% 
  filter(length(segment_id) >= 5)

p1 <- caro_seg_filter %>%
  ggplot(aes(E, N, col = segment_id))  +
  geom_path() +
  geom_point() +
  coord_equal() +
  theme(legend.position = "none")+
  ggtitle("All segments (uncleaned)")

p2 <- caro_seg5 %>%
  ggplot(aes(E, N, col = segment_id))  +
  geom_path() +
  geom_point() +
  coord_equal() +
  theme(legend.position = "none")+
  ggtitle("Long segments (removed segments <5)")

grid.arrange(p1,p2, nrow = 2, top = textGrob("Moving segments colored by ID",gp=gpar(fontsize=16,font=3)))
```

## Task 5
```{r}
ped <- read_delim(file.path(dataFolder, "pedestrian.csv"))
ped <- as.data.frame(ped)
```


```{r}
t1 = ped %>%
  filter(TrajID == 1) %>% 
  ggplot(aes(E, N))  +
  geom_path(col = "red") +
  geom_point(col = "red") +
  coord_equal() +
  theme(legend.position = "none")+
  ggtitle("TrajID: 1")

t2 = ped %>%
  filter(TrajID == 2) %>% 
  ggplot(aes(E, N))  +
  geom_path(col = "brown") +
  geom_point(col = "brown") +
  coord_equal() +
  theme(legend.position = "none")+
  ggtitle("TrajID: 2")

t3 = ped %>%
  filter(TrajID == 3) %>% 
  ggplot(aes(E, N))  +
  geom_path(col = "green") +
  geom_point(col = "green") +
  coord_equal() +
  theme(legend.position = "none")+
  ggtitle("TrajID: 3")

t4 = ped %>%
  filter(TrajID == 4) %>% 
  ggplot(aes(E, N))  +
  geom_path(col = "turquoise") +
  geom_point(col = "turquoise") +
  coord_equal() +
  theme(legend.position = "none")+
  ggtitle("TrajID: 4")

t5 = ped %>%
  filter(TrajID == 5) %>% 
  ggplot(aes(E, N))  +
  geom_path(col = "blue") +
  geom_point(col = "blue") +
  coord_equal() +
  theme(legend.position = "none")+
  ggtitle("TrajID: 5")

t6 = ped %>%
  filter(TrajID == 6) %>% 
  ggplot(aes(E, N))  +
  geom_path(col = "pink") +
  geom_point(col = "pink") +
  coord_equal() +
  theme(legend.position = "none")+
  ggtitle("TrajID: 6")

grid.arrange(t1,t2,t3,t4,t5,t6, nrow = 2, top = textGrob("Visual comparison of the 6 trajectories",gp=gpar(fontsize=16,font=3)))

```

## Task 6

```{r}

```



